float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        args: [
          [True], #quantization
          [ 16 ], #m
          [ 128 ], #ef_construct
          [ True ] # use_grpc
        ]
        query-args: [
          [ 16 ], #hnsw_ef
          [True], # re-score
        ]
