float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        args: [
          [False], # quantization
          [ 16 ], # m
          [ 128 ], # ef_construct
          [ True ]  # use_grpc
        ]
        query-args: [
          [ 8 ], # hnsw_ef
          [ False ], # re-score
        ]
